### ISSUE TITLE
1.4 doesn't install from pip

### ISSUE THREAD

**Issue by Dutcho** [uyar/pygenstub#2]
`pip install pygenstub` fails with File Not Found Error
two versions back is okay `pip install pygenstub==1.2` seems to work

**Comment by uyar** [comment]
@Dutcho I can't reproduce this. I've tried with a clean virtual environment and all of the following commands worked:

```
pip install pygenstub
pip install pygenstub==1.4.0
pip install pygenstub==1.4
```

Version 1.3 was also installed correctly. Could it be related to your pip cache?

**Comment by Dutcho** [comment]
sorry, didn't state what was obvious for me, but you couldn't possibly know:
I run [pip](https://github.com/ywangd/stash/blob/master/bin/pip.py) from [StaSh](https://github.com/ywangd/stash) in [Pythonista](http://omz-software.com/pythonista/index.html) on [iPad](https://www.apple.com/lae/ipad-air/)

**Comment by uyar** [comment]
I don't have access to the environment you're describing but even if I did, I probably wouldn't be able to figure this out since I have no familiarity with these tools. Anyway, the suggested workaround makes sense. pygenstub is a single file script with docutils being the only non-stdlib dependency. I will keep this issue open for a while in case anybody comes up with a solution or with another case where pip install fails.
